CREATE TABLE COUNTRIES 
(
  ID_COUNTRY INT primary key, 
  NAME_COUNTRY VARCHAR(255) NOT NULL,
  CODE_COUNTRY INT NOT NULL,
  CURRENCY VARCHAR(255) NOT NULL
);

CREATE TABLE CITIES 
(
  ID_CITY INT primary key, 
  NAME_CITY VARCHAR(255) NOT NULL, 
  ID_COUNTRY INT NOT NULL,
  CONSTRAINT FK_CITY_COUNTRY  FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRIES(ID_COUNTRY)
);

CREATE TABLE LANGUAGES 
(
  ID_LANGUAGE INT primary key, 
  NAME_LANGUAGE VARCHAR(255) NOT NULL
);

CREATE TABLE PERSONS
(
  ID_PERSON INT primary key, 
  FIRST_NAME VARCHAR(255) NOT NULL, 
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  INVITATION_CODE VARCHAR(255) NOT NULL,
  MOBILE VARCHAR(255) NOT NULL,
  URL_PHOTO VARCHAR(255) NOT NULL,
  ID_CITY INT NOT NULL,
  ID_LANGUAGE INT NOT NULL,
  CONSTRAINT FK_PERSON_COUNTRY  FOREIGN KEY (ID_CITY) REFERENCES CITIES(ID_CITY),
  CONSTRAINT FK_PERSON_LANGUAGE  FOREIGN KEY (ID_LANGUAGE) REFERENCES LANGUAGES(ID_LANGUAGE)
);

CREATE TABLE PAYMENT_METHODS 
(
  ID_PAYMENT INT primary key, 
  DESCRIPTIONS VARCHAR(255) NOT NULL,
  BUSINESS VARCHAR(255) NOT NULL
);

CREATE TABLE PAYMENT_PERSONS
(
  ID_PAYMENT_PERSON INT primary key,  
  ID_PAYMENT INT NOT NULL,
  ID_PERSON INT NOT NULL,
  ACCOUNT_NUMBER VARCHAR(255),
  DATE_EXPEDITION DATE,
  CONSTRAINT FK_PAYMENT_PERSONS_PAYMENT   FOREIGN KEY (ID_PAYMENT) REFERENCES PAYMENT_METHODS(ID_PAYMENT),
  CONSTRAINT FK_PAYMENT_PERSONS_PERSONS   FOREIGN KEY (ID_PERSON) REFERENCES PERSONS(ID_PERSON)
);


CREATE TABLE PROMOTION_CODES 
(
  ID_CODE INT primary key, 
  COURANGE FLOAT NOT NULL,
  DESCRIPTION VARCHAR(255)
);

CREATE TABLE PERSON_CODES
(
  ID_PERSON_CODE INT primary key, 
  ID_PROMOTION_CODE INT NOT NULL, 
  ID_PERSON INT NOT NULL,
  STATUS BOOLEAN,
  CONSTRAINT FK_PERSON_CODE_PROMOTION   FOREIGN KEY (ID_PROMOTION_CODE) REFERENCES PROMOTION_CODES(ID_CODE),
  CONSTRAINT FK_PERSON_CODE_PERSON   FOREIGN KEY (ID_PERSON) REFERENCES PERSONS(ID_PERSON)
);

CREATE TABLE BANKS 
(
  ID_BANK INT primary key, 
  BUSINESS_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE DRIVERS
(
  ID_DRIVER INT primary key, 
  ID_PERSON INT NOT NULL,
  ACCOUNT_NUMBER VARCHAR(255) NOT NULL, 
  ID_BANK INT NOT NULL,
  CONSTRAINT FK_DRIVER_PERSON  FOREIGN KEY (ID_PERSON) REFERENCES PERSONS(ID_PERSON),
  CONSTRAINT FK_DRIVER_BANK   FOREIGN KEY (ID_BANK) REFERENCES BANKS(ID_BANK)
);

CREATE TABLE VEHICLES
(
ID_VEHICLE INT primary key,
LICENSE_PLATE VARCHAR(15) NOT NULL,
BRAND VARCHAR(50),
V_MODEL VARCHAR(50),
V_YEAR INT,
VEHICLE_TYPE INT
);

CREATE TABLE VEHICLES_DRIVERS
(
ID_VEHICLE_DIRVER INT PRIMARY KEY,
ID_VEHICLE INT NOT NULL,
ID_DRIVER INT NOT NULL,
DATE_LINKAGE DATE NOT NULL,
STATUS BOOLEAN,
CONSTRAINT FK_VEHICLES_DRIVERS_VEHICLES  FOREIGN KEY (ID_VEHICLE) REFERENCES VEHICLES(ID_VEHICLE),
  CONSTRAINT FK_VEHICLES_DRIVERS_DRIVERS   FOREIGN KEY (ID_DRIVER) REFERENCES DRIVERS(ID_DRIVER)
);