CREATE TABLE COUNTRIES 
(
  ID_COUNTRY INT primary key, 
  NAME_COUNTRY VARCHAR(255) NOT NULL,
  CODE_COUNTRY INT NOT NULL,
  CURRENCY VARCHAR(255) NOT NULL
);

CREATE TABLE CITIES 
(
  ID_CITY INT primary key, 
  NAME_CITY VARCHAR(255) NOT NULL, 
  ID_COUNTRY INT NOT NULL,
  CONSTRAINT FK_CITY_COUNTRY  FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRIES(ID_COUNTRY)
);

CREATE TABLE LANGUAGES 
(
  ID_LANGUAGE INT primary key, 
  NAME_LANGUAGE VARCHAR(255) NOT NULL
);

CREATE TABLE PERSONS
(
  ID_PERSON INT primary key, 
  FIRST_NAME VARCHAR(255) NOT NULL, 
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  INVITATION_CODE VARCHAR(255) NOT NULL,
  MOBILE VARCHAR(255) NOT NULL,
  URL_PHOTO VARCHAR(255) NOT NULL,
  ID_CITY INT NOT NULL,
  ID_LANGUAGE INT NOT NULL,
  CONSTRAINT FK_PERSON_COUNTRY  FOREIGN KEY (ID_CITY) REFERENCES CITIES(ID_CITY),
  CONSTRAINT FK_PERSON_LANGUAGE  FOREIGN KEY (ID_LANGUAGE) REFERENCES LANGUAGES(ID_LANGUAGE)
);

CREATE TABLE PAYMENT_METHODS 
(
  ID_PAYMENT INT primary key, 
  DESCRIPTIONS VARCHAR(255) NOT NULL,
  BUSINESS VARCHAR(255) NOT NULL
);

CREATE TABLE PAYMENT_PERSONS
(
  ID_PAYMENT_PERSON INT primary key,  
  ID_PAYMENT INT NOT NULL,
  ID_PERSON INT NOT NULL,
  ACCOUNT_NUMBER VARCHAR(255),
  DATE_EXPEDITION DATE,
  CONSTRAINT FK_PAYMENT_PERSONS_PAYMENT   FOREIGN KEY (ID_PAYMENT) REFERENCES PAYMENT_METHODS(ID_PAYMENT),
  CONSTRAINT FK_PAYMENT_PERSONS_PERSONS   FOREIGN KEY (ID_PERSON) REFERENCES PERSONS(ID_PERSON)
);